//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Serializable()]
public class ObstacleInfo
{
    
    public int id;
    
    public int kind;
    
    public int cellX;
    
    public int cellY;
    
    public float posX;
    
    public float posY;
    
    public float posZ;

    public bool active;
}
